### ISSUE TITLE
JSON/RSS representation of the tips

### ISSUE THREAD

**Issue by ahmetws** [MobileTipsters/Swift-Daily-Tips#52]
I want to make an experiment website with server-side Swift Vapor framework. I need a JSON/RSS file to get all the tips data.

There are a lot of people using RSS feeds to track their favorite sources. We can also add one.

**Comment by chengp0819** [comment]
> I want to make an experiment website with server-side Swift Vapor framework. I need a JSON/RSS file to get all the tips data.
> 
> There are a lot of people using RSS feeds to track their favorite sources. We can also add one.

good idea

**Comment by alicanbatur** [comment]
It could be nice. We can create RSS with your support? We also want to help you with your Vapor project!

**Comment by emreozdil** [comment]
[Add JSON Representation](https://github.com/MobileTipsters/Swift-Daily-Tips/commit/2923b740b7f8f20a6846b3a6f48604a3c79d1f87)
